### ISSUE TITLE
The Create Sample - panel does not display dates and compounds

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#702] opened 2016-08-22 15:12 UTC
In the side panel for the Create Sample template, when updated, the dates (e.g. Manufacture date) and the parts of the compounds are not being shown.

**Comment by Terry-Weymouth** [comment] 2016-08-22 19:44
Duplicates issue-709?

**Comment by gtarcea** [comment] 2016-08-24 15:08
This issue is a duplicate of #709.

**Closed by gtarcea** 2016-08-24 15:08 UTC
